# Generated by Django 3.2.12 on 2022-03-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShiftManagementApp', '0003_auto_20220301_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='begin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='shift',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='shift',
            name='finish',
            field=models.DateTimeField(),
        ),
    ]
