# Generated by Django 3.2.12 on 2022-03-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShiftManagementApp', '0004_auto_20220301_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(verbose_name='ユーザーID'),
        ),
    ]
