# Generated by Django 3.2.12 on 2022-03-05 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShiftManagementApp', '0008_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='user_id',
            new_name='user',
        ),
    ]
