# Generated by Django 3.2.12 on 2022-03-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShiftManagementApp', '0009_rename_user_id_shift_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_position',
            field=models.BooleanField(default=True, verbose_name='default_position'),
            preserve_default=False,
        ),
    ]
