# Generated by Django 3.2.12 on 2022-05-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShiftManagementApp', '0013_line_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='line_user_id',
            name='nonce',
            field=models.CharField(max_length=100, null=True, verbose_name='nonce'),
        ),
    ]
