# Generated by Django 3.2.12 on 2022-05-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShiftManagementApp', '0015_rename_user_id_line_user_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line_user_id',
            name='line_user_id',
            field=models.CharField(max_length=50, null=True, verbose_name='line_user_id'),
        ),
    ]
