# Generated by Django 3.2.12 on 2022-05-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShiftManagementApp', '0016_alter_line_user_id_line_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_edit_mode',
            field=models.BooleanField(default=False, verbose_name='is_edit_mode'),
        ),
    ]
