# Generated by Django 3.2.12 on 2022-05-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShiftManagementApp', '0017_user_is_edit_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publish_range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Publish_shift_start', models.DateField(verbose_name='Publish_shift_start')),
                ('Publish_shift_end', models.DateField(verbose_name='Publish_shift_end')),
            ],
        ),
        migrations.AddField(
            model_name='shift',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='publish'),
        ),
    ]
