# Generated by Django 3.2.12 on 2022-08-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShiftManagementApp', '0018_auto_20220526_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='publish',
            field=models.BooleanField(default=False, verbose_name='publish'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
    ]
