# Generated by Django 3.2.12 on 2022-08-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShiftManagementApp', '0019_auto_20220808_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_pwa_user',
            field=models.BooleanField(default=False, verbose_name='pwa_user'),
        ),
    ]
