version: 2.1
orbs: 
  heroku-container: pbrisbin/heroku-container@1.0.0
  aws-ecr: circleci/aws-ecr@8.1.2

jobs: 
  test: 
    docker: 
      - image: python:3.9.13
      - image: circleci/postgres
        environment: 
          POSTGRES_DB: dtvn6smssuuna
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    environment: 
          DATABASE_URL: postgres://postgres:postgres@127.0.0.1:5432/dtvn6smssuuna
          EMAIL_HOST_PASSWORD: $EMAIL_HOST_PASSWORD
          SECRET_KEY: $SECRET_KEY

    steps: 
      - checkout
      - run: pip install -r requirements.txt
      - run: python manage.py makemigrations
      - run: python manage.py migrate
      - run: python manage.py collectstatic --noinput
      - run: python3 manage.py test
workflows: 
  test_and_build:
    jobs: 
      - test 
      - heroku-container/push-and-release:
          app-name: shiftmanagementapp-heroku
          filters: 
            branches: 
              only: 
                - main
          requires: 
            - test
      - aws-ecr/build-and-push-image: 
          region: ap-northeast-1
          repo: django
          tag: latest
          public-registry: true
          filters:
            branches:
              only:
                - main
          requires:
            - test
