version: 2.1
orbs: 
  heroku-container: pbrisbin/heroku-container@1.0.0

jobs: 
  create_test_postgres: 
    docker: 
      - image: python:3.9.13
        environment:
          POSTGRES_PASSWORD: admin
          POSTGRES_USER: admin
      - image: circleci/postgres
        environment: 
          POSTGRES_DB: dtvn6smssuuna
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
<<<<<<< HEAD
=======
    environment: 
          DATABASE_URL: postgres://admin:admin@localhost/dtvn6smssuuna

>>>>>>> 7acf548f8fa026b5989701383f824bbac982cfa2
    steps: 
      - checkout
      - run: echo 'export EMAIL_HOST_PASSWORD=$EMAIL_HOST_PASSWORD'
      - run: echo 'export SECRET_KEY=$SECRET_KEY'
      - run: pip install -r requirements.txt
      - run: python3 manage.py test
workflows: 
  create_test_postgres:
    jobs: 
      - create_test_postgres 
      - heroku-container/push-and-release:
          app-name: shiftmanagementapp-heroku
          filters: 
            branches: 
              only: 
                - main
          requires: 
            - create_test_postgres
