version: 2.1
orbs: 
  heroku-container: pbrisbin/heroku-container@1.0.0
  aws-ecr: circleci/aws-ecr@8.1.2
  cloudrun: circleci/gcp-cloud-run@x.y

jobs: 
  test: 
    docker: 
      - image: python:3.9.13
      - image: circleci/postgres
        environment: 
          POSTGRES_DB: dtvn6smssuuna
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    environment: 
          DATABASE_URL: postgres://postgres:postgres@127.0.0.1:5432/dtvn6smssuuna
          EMAIL_HOST_PASSWORD: $EMAIL_HOST_PASSWORD
          SECRET_KEY: $SECRET_KEY

    steps: 
      - checkout
      - run: pip install -r requirements.txt
      - run: python manage.py makemigrations
      - run: python manage.py migrate
      - run: python manage.py collectstatic --noinput
      - run: python3 manage.py test
  build_and_deploy_cloud_run: 
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - cloudrun/init
      - cloudrun/build:
          tag: 'us-central1-docker.pkg.dev/shiftmanagementapp-363812/shiftmanagementapp'
      - cloudrun/deploy:
          image: 'us-central1-docker.pkg.dev/shiftmanagementapp-363812/shiftmanagementapp/app'
          platform: managed
          region: us-east1
          service-name: shiftmanagementapp
          unauthenticated: true
workflows: 
  test_and_build:
    jobs: 
      - test 
      - heroku-container/push-and-release:
          app-name: shiftmanagementapp-heroku
          filters: 
            branches: 
              only: 
                - main
          requires: 
            - test
      - aws-ecr/build-and-push-image: 
          repo: django
          tag: latest
          public-registry: true
          filters:
            branches:
              only:
                - main
          requires:
            - test
      - build_and_deploy_to_cloudrun: 
          filters: 
            branches: 
             - main
          requires: 
            - test
