version: 2.1
orbs: 
  heroku-container: pbrisbin/heroku-container@1.0.0

jobs: 
  create_test_postgres: 
    docker: 
      - image: circleci/postgres
        environment: 
          - POSTGRES_DB: dtvn6smssuuna
  test: 
    docker: 
      - image: python:3.9.13
    steps: 
      - checkout
      - run: echo 'export EMAIL_HOST_PASSWORD=$EMAIL_HOST_PASSWORD'
      - run: echo 'export SECRET_KEY=$SECRET_KEY'
      - run: pip install -r requirements.txt
      - run: python3 manage.py test
    
  build_and_release: 
    heroku-container/push-and-release:
      app-name: shiftmanagementapp-heroku
      filters: 
        branches: 
          only: 
            - main