version: 2.1
orbs: 
  heroku-container: pbrisbin/heroku-container@1.0.0
workflows: 
  build_and_release: 
    jobs: 
      - heroku-container/push-and-release:
        app-name: shiftmanagementapp-heroku
        filters: 
          branches: 
            only: 
            - main