version: 2.1
orbs: 
  heroku-container: pbrisbin/heroku-container@1.0.0

jobs: 
  test: 
    docker: 
      - image: python:3.9.13
    steps: 
      - checkout
      - run: echo 'export EMAIL_HOST_PASSWORD=$EMAIL_HOST_PASSWORD'
      - run: pip install -r requirements.txt
      - run: python3 manage.py test
workflows: 
  build_and_release: 
    jobs: 
      - test
      - heroku-container/push-and-release:
          app-name: shiftmanagementapp-heroku
          filters: 
            branches: 
              only: 
                - main
workflows: 
  all-check: 
    jobs: 
      - test
      - build_and_release: 
        requires: 
          - test