name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.SERVER_DEPLOY_DIR }}
            git pull origin main
            source /home/${{ secrets.SERVER_USERNAME }}/venv/bin/activate
            pkill gunicorn
            gunicorn config.wsgi --bind=0.0.0.0:8000 -D
            python3 manage.py collectstatic --noinput
            sudo systemctl restart nginx